### ISSUE TITLE
ВалидацияЧисла

### ISSUE THREAD

**Issue by AntSidorov** [Segate-ekb/1c_OpenApi_validation#10]
В функциях ПроверитьМинимум и ПроверитьМаксимум  некорректно проверяется граница включения.
Если переменная Включая = Истина, то выходит ошибка вида:
Ошибка валидации <version>. Значение <1> должно быть больше или равно <1>

**Comment by Segate-ekb** [comment]
Привет, приложи пожалуйста схему и json

**Comment by Segate-ekb** [comment]
воспроизвел, сейчас поправлю

**Comment by Segate-ekb** [comment]
@AntSidorov Сборка с фиксом.
[1c_validator-0.0.3.2.zip](https://github.com/user-attachments/files/17992663/1c_validator-0.0.3.2.zip)
